sudo: required
services:
  - docker

before_install:
  - docker build -t vasanth/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vasanth/react-test npm test 

after_sucess:
  - docker build -t vasanth/multi-client ./client
  - docker build -t vasanth/multi-nginx ./nginx
  - docker build -t vasanth/multi-server ./server
  - docker build -t vasanth/multi-worker ./worker
  
  # log in to thte docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those image and push them to docker hub
  - docker push vasanth/multi-client
  - docker push vasanth/multi-nginx
  - docker push vasanth/multi-server
  - docker push vasanth/multi-worker

