language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vasanth195500/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vasanth195500/react-test npm test


after_success:
  - docker build -t vasanth195500/multi-client ./client
  - docker build -t vasanth195500/multi-nginx ./nginx
  - docker build -t vasanth195500/multi-server ./server
  - docker build -t vasanth195500/multi-worker ./worker
  # log in to thte docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those image and push them to docker hub
  - docker push vasanth195500/multi-client
  - docker push vasanth195500/multi-nginx
  - docker push vasanth195500/multi-server
  - docker push vasanth195500/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-214002746327
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: AKIATDU4OYPLWYPVOVGY
  secret_access_key:
    secure: 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